CLEVR_TEST_COMMON_CFG = dict(
    filename=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
    image_folder=
    'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
    scene_graph_file=None,
    type='ClevrDataset')
DEFAULT_TEST_CLEVR_VARIANT = dict(
    CLEVR_A_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='ClevrDataset',
        version='q-a'),
    CLEVR_BS_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_PCoT.json',
        type='ClevrDataset',
        version='q-a'),
    CLEVR_S_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='ClevrDataset',
        version='q-a'))
DEFAULT_TEST_DATASET = dict(
    CLEVR_A_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='ClevrDataset',
        version='q-a'),
    CLEVR_BS_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_PCoT.json',
        type='ClevrDataset',
        version='q-a'),
    CLEVR_S_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CLEVR_val_questions_with_ans.jsonl',
        image_folder=
        'zz1424:s3://publicdataset_33/CLEVR/unzip/CLEVR_v1.0/images/val',
        scene_graph_file=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='ClevrDataset',
        version='q-a'),
    COCO_POPE_ADVERSARIAL_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_adversarial.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_ADVERSARIAL_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_adversarial.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'),
    COCO_POPE_POPULAR_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_popular.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_POPULAR_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_popular.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'),
    COCO_POPE_RANDOM_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_random.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_RANDOM_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_random.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'),
    FLICKR_EVAL_with_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_eval.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/flickr30k.json',
        type='FlickrDataset'),
    FLICKR_EVAL_without_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_eval.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/image_cap.json',
        type='FlickrDataset'),
    FLICKR_TEST_with_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/flickr30k.json',
        type='FlickrDataset'),
    FLICKR_TEST_without_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/image_cap.json',
        type='FlickrDataset'),
    GPT4GEN_QA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GPT4Gen',
        version='a'),
    GPT4GEN_QBC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GPT4Gen',
        version='bc'),
    GPT4GEN_QC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GPT4Gen',
        version='c'),
    GQA_Q_A=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_A_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_BC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_BC_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_C=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_C_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GQADataset',
        version='q-a'),
    POINT_LOCAL_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='b'),
    POINT_LOCAL_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='b'),
    POINT_LOCAL_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='p'),
    POINT_LOCAL_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='p'),
    POINT_TWICE_gq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-b'),
    POINT_TWICE_gq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-b'),
    POINT_TWICE_gq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-p'),
    POINT_TWICE_gq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-p'),
    POINT_TWICE_oq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-b'),
    POINT_TWICE_oq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-b'),
    POINT_TWICE_oq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-p'),
    POINT_TWICE_oq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-p'),
    POINT_TWICE_sq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-b'),
    POINT_TWICE_sq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-b'),
    POINT_TWICE_sq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-p'),
    POINT_TWICE_sq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-p'),
    POINT_V7W_b_test=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='b'),
    POINT_V7W_b_val=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='b'),
    POINT_V7W_p_test=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='p'),
    POINT_V7W_p_val=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='p'),
    REC_REFCOCOA_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOA_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOA_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOG_UMD_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_umd_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOG_UMD_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_umd_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REG_REFCOCOG_GOOGLE_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_google_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REG.json',
        type='REGDataset'),
    RES_REFCOCOA_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOA_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOA_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOG_UMD_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcocog_umd_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOG_UMD_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcocog_umd_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    VCR_test_qac_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qac-r'),
    VCR_test_qc_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qc-a'),
    VCR_test_qc_a_qc_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qc-a-qc-r'),
    VCR_test_qc_rac=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRPredDataset',
        version='qc-rac'),
    VCR_val_q_ra=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRDataset',
        version='q-ra'),
    VCR_val_qac_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qac-r'),
    VCR_val_qc_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qc-a'),
    VCR_val_qc_a_qc_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qc-a-qc-r'),
    VCR_val_qc_rac=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRDataset',
        version='qc-rac'),
    VQAv2_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_test2015_questions.jsonl',
        has_annotation=False,
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'),
    VQAv2_testdev=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_test-dev2015_questions.jsonl',
        has_annotation=False,
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'),
    VQAv2_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_val2014_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'))
DEFAULT_TEST_FLICKR_VARIANT = dict(
    FLICKR_EVAL_with_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_eval.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/flickr30k.json',
        type='FlickrDataset'),
    FLICKR_EVAL_without_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_eval.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/image_cap.json',
        type='FlickrDataset'),
    FLICKR_TEST_with_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/flickr30k.json',
        type='FlickrDataset'),
    FLICKR_TEST_without_box=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/CWB_flickr30k_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/image_cap.json',
        type='FlickrDataset'))
DEFAULT_TEST_GPTGEN_VARIANT = dict(
    GPT4GEN_QA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GPT4Gen',
        version='a'),
    GPT4GEN_QBC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GPT4Gen',
        version='bc'),
    GPT4GEN_QC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GPT4Gen',
        version='c'))
DEFAULT_TEST_GQA_VARIANT = dict(
    GQA_Q_A=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_A_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_BC=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_BC_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_C=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_all_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GQADataset',
        version='q-a'),
    GQA_Q_C_BALANCED=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/gqa_testdev_balanced_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/gqa/images',
        scene_graph_file=None,
        scene_graph_index=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_CoT.json',
        type='GQADataset',
        version='q-a'))
DEFAULT_TEST_POINT_VARIANT = dict(
    POINT_LOCAL_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='b'),
    POINT_LOCAL_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='b'),
    POINT_LOCAL_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='p'),
    POINT_LOCAL_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_local_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_local',
        version='p'),
    POINT_TWICE_gq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-b'),
    POINT_TWICE_gq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-b'),
    POINT_TWICE_gq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-p'),
    POINT_TWICE_gq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='gq-p'),
    POINT_TWICE_oq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-b'),
    POINT_TWICE_oq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-b'),
    POINT_TWICE_oq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-p'),
    POINT_TWICE_oq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='oq-p'),
    POINT_TWICE_sq_b_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-b'),
    POINT_TWICE_sq_b_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-b'),
    POINT_TWICE_sq_p_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-p'),
    POINT_TWICE_sq_p_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/pointQA_twice_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vg',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='Point_QA_twice',
        version='sq-p'),
    POINT_V7W_b_test=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='b'),
    POINT_V7W_b_val=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='b'),
    POINT_V7W_p_test=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='p'),
    POINT_V7W_p_val=dict(
        do_shuffle_choice=True,
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v7w_pointing_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='V7W_POINT',
        version='p'))
DEFAULT_TEST_POPE_VARIANT = dict(
    COCO_POPE_ADVERSARIAL_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_adversarial.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_ADVERSARIAL_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_adversarial.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'),
    COCO_POPE_POPULAR_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_popular.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_POPULAR_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_popular.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'),
    COCO_POPE_RANDOM_q_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_random.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='POPEVQADataset'),
    COCO_POPE_RANDOM_q_bca=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_random.json',
        image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='POPEVQADataset'))
DEFAULT_TEST_REC_VARIANT = dict(
    REC_REFCOCOA_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOA_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOA_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco+_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOG_UMD_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_umd_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCOG_UMD_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_umd_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'),
    REC_REFCOCO_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcoco_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RECDataset'))
DEFAULT_TEST_REFCOCOG_VARIANT = dict(
    REG_REFCOCOG_GOOGLE_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/REC_refcocog_google_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REG.json',
        type='REGDataset'))
DEFAULT_TEST_RES_VARIANT = dict(
    RES_REFCOCOA_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOA_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOA_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco+_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOG_UMD_TEST=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcocog_umd_test.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCOG_UMD_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcocog_umd_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_TESTA=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_testA.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_TESTB=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_testB.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'),
    RES_REFCOCO_UNC_VAL=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/RES_refcoco_unc_val.jsonl',
        image_folder=
        '/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
        max_dynamic_size=None,
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
        type='RESDataset'))
DEFAULT_TEST_VCR_VARIANT = dict(
    VCR_test_qac_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qac-r'),
    VCR_test_qc_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qc-a'),
    VCR_test_qc_a_qc_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRPredDataset',
        version='qc-a-qc-r'),
    VCR_test_qc_rac=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRPredDataset',
        version='qc-rac'),
    VCR_val_q_ra=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRDataset',
        version='q-ra'),
    VCR_val_qac_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qac-r'),
    VCR_val_qc_a=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qc-a'),
    VCR_val_qc_a_qc_r=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VCRDataset',
        version='qc-a-qc-r'),
    VCR_val_qc_rac=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA_BCoT.json',
        type='VCRDataset',
        version='qc-rac'))
DEFAULT_TEST_VQAv2_VARIANT = dict(
    VQAv2_test=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_test2015_questions.jsonl',
        has_annotation=False,
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'),
    VQAv2_testdev=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_test-dev2015_questions.jsonl',
        has_annotation=False,
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'),
    VQAv2_val=dict(
        filename=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/v2_OpenEnded_mscoco_val2014_questions.jsonl',
        image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
        template_file=
        '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
        type='VQAv2Dataset'))
FLICKR_TEST_COMMON_CFG = dict(
    image_folder=
    '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
    max_dynamic_size=None,
    type='FlickrDataset')
GPTGEN_TEST_COMMON_CFG = dict(
    filename=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/GPT4GEN_BoxCoT_test.jsonl',
    image_folder=
    '/data/public/multimodal/multimodal_data/flickr30k/flickr30k-images',
    type='GPT4Gen')
GQA_TEST_COMMON_CFG = dict(
    image_folder='/data/public/multimodal/multimodal_data/gqa/images',
    scene_graph_file=None,
    scene_graph_index=None,
    type='GQADataset')
POINT_TEST_COMMON_CFG_LOCAL = dict(
    image_folder='/data/public/multimodal/multimodal_data/vg',
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
    type='Point_QA_local')
POINT_TEST_COMMON_CFG_TWICE = dict(
    image_folder='/data/public/multimodal/multimodal_data/vg',
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
    type='Point_QA_twice')
POINT_TEST_COMMON_CFG_V7W = dict(
    do_shuffle_choice=True,
    image_folder='/data/public/multimodal/multimodal_data/visual7w/images',
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
    type='V7W_POINT')
POPE_TEST_COMMON_CFG = dict(
    image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
    type='POPEVQADataset')
REC_TEST_COMMON_CFG = dict(
    image_folder='/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
    max_dynamic_size=None,
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
    type='RECDataset')
REG_CAP_TEST_COMMON_CFG = dict(
    image_folder='/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
    max_dynamic_size=None,
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REG.json',
    type='REGDataset')
RES_TEST_COMMON_CFG = dict(
    image_folder='/data/public/multimodal/multimodal_data/coco_imgs/train2014/',
    max_dynamic_size=None,
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/REC.json',
    type='RESDataset')
VCR_TEST_COMMON_CFG = dict(
    filename=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_test.jsonl',
    image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
    type='VCRPredDataset')
VCR_VAL_COMMON_CFG = dict(
    filename=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/../../../data/vcr_val.jsonl',
    image_folder='/data/public/multimodal/multimodal_data/vcr/vcr1images',
    type='VCRDataset')
VQAv2_TEST_COMMON_CFG = dict(
    image_folder='/data/public/multimodal/multimodal_data/coco_imgs',
    template_file=
    '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
    type='VQAv2Dataset')
data_args = dict(
    collator_kwargs=dict(max_length=1024, padding=True),
    compute_metric=None,
    gen_kwargs=dict(max_new_tokens=20, num_beams=1),
    multitest=dict(
        COCO_POPE_ADVERSARIAL_q_a=dict(
            cfg=dict(
                filename=
                '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_adversarial.json',
                image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
                template_file=
                '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
                type='POPEVQADataset'),
            compute_metric=dict(type='PopeComputeMetrics')),
        COCO_POPE_POPULAR_q_a=dict(
            cfg=dict(
                filename=
                '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_popular.json',
                image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
                template_file=
                '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
                type='POPEVQADataset'),
            compute_metric=dict(type='PopeComputeMetrics')),
        COCO_POPE_RANDOM_q_a=dict(
            cfg=dict(
                filename=
                '/lustre/fs1/home/sghosh2/NExT-Chat/POPE/coco_pope_random.json',
                image_folder='/lustre/fs1/home/sghosh2/NExT-Chat/coco/val2014',
                template_file=
                '/lustre/fs1/home/sghosh2/NExT-Chat/config/_base_/dataset/template/VQA.json',
                type='POPEVQADataset'),
            compute_metric=dict(type='PopeComputeMetrics'))),
    test=None,
    train=None,
    validation=None)
model_args = dict(
    cache_dir=None,
    conv_args=dict(
        conv_template='vicuna_v1.1',
        tokenize_kwargs=dict(truncation_size=2048),
        transforms=dict(type='Expand2square')),
    freeze_backbone=False,
    freeze_mm_mlp_adapter=False,
    gen_kwargs_set_bos_token_id=True,
    gen_kwargs_set_eos_token_id=True,
    gen_kwargs_set_pad_token_id=True,
    image_token_len=576,
    mm_projector_depth=2,
    mm_use_im_start_end=True,
    mm_vision_select_layer=-2,
    model_max_length=2048,
    model_name_or_path='/lustre/fs1/home/sghosh2/NExT-Chat/nextchat-7b-336',
    pretrain_mm_mlp_adapter=None,
    pretrained_mm_projector=None,
    process_func_args=dict(
        conv=dict(type='ChatConvProcess'),
        image=dict(type='ChatImageProcessor'),
        target=dict(type='BoxFormatProcess'),
        text=dict(type='ChatTextProcess')),
    sam_path='/home/sghosh2/NExT-Chat/SAM/sam_vit_h_4b8939.pth',
    sep_image_conv_front=False,
    target_processor=dict(boxes=dict(type='PlainBoxFormatter')),
    tune_mm_mlp_adapter=False,
    type='nextchat',
    version='v1',
    vision_tower='/home/sghosh2/NExT-Chat/openai/clip-vit-large-patch14-336')
training_args = dict(
    bf16=True,
    bf16_full_eval=True,
    do_eval=False,
    do_multi_predict=True,
    do_predict=False,
    do_train=False,
    fp16=False,
    fp16_full_eval=False,
    logging_steps=1,
    output_dir='/lustre/fs1/home/sghosh2/NExT-Chat/nextchat-7b-336/pope/',
    overwrite_output_dir=False,
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    remove_unused_columns=False,
    report_to='none',
    seed=42)
